import React from 'react'

// Mock data for products
const mockProducts = [
    {
      id: 1,
      name: 'Smartphone X',
      price: 999.99,
      description: 'Latest model with advanced features.',
      image: require('../assets/Smartphone X.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 2,
      name: 'Laptop Pro',
      price: 1299.99,
      description: 'High performance laptop.',
      image: require('../assets/Laptop Pro.jpeg' ),
      with: 100,
      height: 200,
    },
    {
      id: 3,
      name: 'Wireless Earbuds',
      price: 199.99,
      description: 'Noise-cancelling earbuds with long battery life.',
      image: require('../assets/Wireless Earbuds.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 4,
      name: 'Samsung Galaxy S24 Ultra',
      price: 199.99,
      description: 'Noise-cancelling earbuds with long battery life.',
      image: require('../assets/SamsungGalaxyS24.jpg'),
      with: 100,
      height: 200,
    },
    {
      id: 5,
      name: 'Smart Watch',
      price: 299.99,
      description: 'Stay connected with this stylish smart watch.',
      image: require('../assets/Smart Watch.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 6,
      name: 'Bluetooth Speaker',
      price: 99.99,
      description: 'Portable speaker with excellent sound quality.',
      image: require('../assets/Bluetooth Speaker.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 7,
      name: 'Gaming Console',
      price: 499.99,
      description: 'Next-gen console for immersive gaming experiences.',
      image: require('../assets/Gaming Console.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 8,
      name: 'Digital Camera',
      price: 599.99,
      description: 'Capture your moments with high precision.',
      image: require('../assets/Digital Camera.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 9,
      name: 'Drone',
      price: 899.99,
      description: 'High-performance drone for aerial photography.',
      image: require('../assets/Drone.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 10,
      name: 'VR Headset',
      price: 399.99,
      description: 'Experience virtual reality with this VR headset.',
      image: require('../assets/VR Headset.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 11,
      name: '4K OLED TV',
      price: 1499.99,
      description: 'Ultra HD TV with stunning picture quality.',
      image: require('../assets/OLED TV.jpeg'),
      with: 100,
      height: 200,
    },
    {
      id: 12,
      name: 'All Devices ',
      price: 1499.99,
      description: 'All Devices with stunning picture quality.',
      image: require('../assets/product1.jpeg'),
      with: 100,
      height: 200,
    },
    // Add more products as needed
  ];

export default mockProducts
